name: foodapp
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  provider: ^6.0.1
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  isar: ^3.1.0+1
  freezed_annotation: ^2.4.1
  http: ^1.2.1
  json_annotation: ^4.9.0 
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.3
  isar_flutter_libs: ^3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.1.1
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
